### ISSUE TITLE
Export crawled data

### ISSUE THREAD

**Issue by umpirsky** [scrapy/dirbot#16]
Sorry if this is a noobish question, but is there a way to export crawled data to csv or some handy format?

Or that is out of the scope of this example?

**Comment by MohanL** [comment]
@umpirsky pretty sure python fileio could solve your problem

**Comment by umpirsky** [comment]
@MohanL Thanks.

No, I know there are awesome tools. I especially like http://petl.readthedocs.org/en/latest/intro.html#functional-and-object-oriented-programming-styles.

I just wanted to make sure that this is out of scrapy scope.

**Comment by umpirsky** [comment]
@MohanL Actually you can:

`$ scrapy runspider dirbot/spiders/dmoz.py -o items.csv -t csv`

Result it:

```
$ car items.csv
url,description,name
"http://www.pearsonhighered.com/educator/academic/product/0,,0130260363,00%2Ben-USS_01DBC.html","- By Wesley J. Chun; Prentice Hall PTR, 2001, ISBN 0130260363. For experienced developers to improve extant skills; professional level examples. Starts by introducing syntax, objects, error handling, functions, classes, built-ins. [Prentice Hall]
",Core Python Programming
http://www.brpreiss.com/books/opus7/html/book.html,"- The primary goal of this book is to promote object-oriented design using Python and to illustrate the use of the emerging object-oriented design patterns.
",Data Structures and Algorithms with Object-Oriented Design Patterns in Python
http://www.diveintopython.net/,"- By Mark Pilgrim, Guide to Python 3  and its differences from Python 2. Each chapter starts with a real code sample and explains it fully. Has a comprehensive appendix of all the syntactic and semantic changes in Python 3
",Dive Into Python 3
...
```

**Comment by Copser** [comment]
Actually Python have it's own [csv module](https://docs.python.org/3/library/csv.html) for that purpose, so you can crawl the data in any known format and than play whit the python csv module. Just check the docs.

**Comment by umpirsky** [comment]
@Copser Yes, but with `-o items.csv -t csv` no coding required.

**Comment by Copser** [comment]
Yes I know that, you can scrape every format like that, just wanted to tell
you that there is a python module if you need anything more from your csv
;-)

**Comment by umpirsky** [comment]
@Copser Thanks. :+1:
