### ISSUE TITLE
Is scrapy/dirbot a second instance / an off shoot example of the scrapy tutorial?

### ISSUE THREAD

**Issue by Karla-Isabel-Sandoval** [scrapy/dirbot#18]
this part was not entirely clear in the read.me

**Comment by redapple** [comment]
@Karla-Isabel-Sandoval , this project was following Scrapy's tutorial until recently.
But dmoz.org changed layout a few times (and exists no more, [https://github.com/scrapy/dirbot/pull/28](replaced by http://dmoztools.net/) it seems)
As it depended on a website that could change layout, it was becoming hard to keep in sync with it.
Hence we decided to rewrite Scrapy tutorial with an example website that does not change: http://quotes.toscrape.com/

I've marked this repository as deprecated as of March 2017. Code is left for reference, but there's little chance that we'll update it in the foreseeable future.
