### ISSUE TITLE
Dmoz site change

### ISSUE THREAD

**Issue by paulojblack** [scrapy/dirbot#19]
Dmoz just changed the layout of their site so this scraper is no longer usable.

**Comment by ialsaud** [comment]
I was able to make the project run by changing dmoz.py line 24.
`#from
sites = sel.xpath('//ul[@class="directory-url"]/li')
#to
sites = sel.xpath('//ul/li')`

**Comment by zhchaoo** [comment]
Replace the  xpath('//ul[@class="directory-url"]/li') with xpath('//ul[@class="title-and-desc"]') will be ok

**Comment by zhchaoo** [comment]
I replace
sites = sel.xpath('//ul[@class="directory-url"]/li')
to
sites = sel.xpath('//div[@class="title-and-desc"]')

and replace
item['name'] = site.xpath('a/text()').extract()
item['url'] = site.xpath('a/@href').extract()
item['description'] = site.xpath('text()').re('-\s[^\n]*\\r')
to
item['name'] = site.xpath('a/div/text()').extract()
item['url'] = site.xpath('a/@href').extract()
item['description'] = site.xpath('div/text()').re('\w[^\n\r]*')

and it seems work fine

**Comment by Sunnysunny321** [comment]
Something modified by zhchaoo  may be usable before, but now it is invalid.
Just replace 
item['description'] = site.xpath('div[@class="site-descr "]/text()').re('\w[^\n\r]')
with
_**item['description'] = site.xpath('div/text()').extract()**_
based on zhchaoo

**Comment by wardwissner** [comment]
Very confused.  I took the following script from the scrappy tutorial.  Is there an easy way for me to revise this since I understand the Dmoz site has changed.
import scrapy

from tutorial_new.items import DmozItem

class DmozSpider(scrapy.Spider):
    name = "dmoz"
    allowed_domains = ["dmoz.org"]
    start_urls = [
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Books/",
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/"
    ]

    def parse(self, response):
        for sel in response.xpath('//ul/li'):
            item = DmozItem()
            item['title'] = sel.xpath('a/text()').extract()
            item['link'] = sel.xpath('a/@href').extract() 
            item['desc'] = sel.xpath('text()').extract()
            yield item


Please help

**Comment by eliasdorneles** [comment]
Sorry for taking long to fix this !
We've merged #21 who fix for new layout and adds Python 3 compatibility.

We're starting a new [quotesbot project](https://github.com/scrapy/quotesbot) that will use quotes.toscrape.com just like the newly updated tutorial and will be better maintained.

Thanks again!! :+1:
